Add force option to overwrite destination files

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -4,6 +4,20 @@ export DOTFILES=~/.dotfiles
 shopt -s dotglob
 
 REPO_URL=https://github.com/jamesmcfadden/dotfiles
+FORCE=false
+
+while getopts ":f" opt; do
+  case $opt in
+    f)
+      echo "Forcing..."
+      FORCE=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
 
 if [[ ! -d $DOTFILES ]]
 then
@@ -18,15 +32,25 @@ fi
 for f in $DOTFILES/link/*
 do
   dest=~/${f##*/}
-  echo "[LINK] $f --> $dest"
-  ln -sf $f $dest
+  if [[ -e $dest && $FORCE = false ]]
+  then
+    echo "! $dest already exists, not symlinking"
+  else
+    echo "[LINK] $f --> $dest"
+    ln -sf $f $dest
+  fi
 done
 
 for f in $DOTFILES/copy/*
 do
   dest=~/${f##*/}
-  echo "[COPY] $f --> $dest"
-  cp $f $dest
+  if [[ -e $dest && $FORCE = false ]]
+  then
+    echo "! $dest already exists, not copying"
+  else
+    echo "[COPY] $f --> $dest"
+    cp $f $dest
+  fi
 done
 
 echo "Finished"
